### ISSUE TITLE
Optimize the cache refresh mechanism

### ISSUE THREAD

**Issue by MatrixHB** [apache/rocketmq-schema-registry#3]
Schema registry uses RocksDB as local cache and uses RocketMQ (compact topic) as remote storage.  Now the local cache refresh is implemented by pushConsumer consuming messages from RocketMQ. I found two problems with current code.

1、Using pushConsumer in cluster mode, it must be ensured that each node is a different consumer group, otherwise each node cannot synchronize the complete data.

2、Lack of replay mechanism. When a registry node restart with incomplete local cache, or cold start with empty local cache, we need to pull the complete data from RocketMQ storage to recover the local cache. Therefore, it's better to maintain checkpoint and use pullConsumer to seek specified offset, which is also the suggested way to consume compact topic messages.

**Comment by ferrirW** [comment]
There is no good way to solve the second problem right now. Unless RocketMQ COMPACTION Topic can provides semantics like KV.

And i think the first problem also exists in pull mode, we can use ip / hostname / nodeId to ensure that the consumer group is unique.
