### ISSUE TITLE
Should provide an interface to obtain the schema by ID 

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq-schema-registry#61]
It should provide an interface to obtain the schema by ID to ensure that the schema used for serialization and deserialization is consistent

![image](https://user-images.githubusercontent.com/6446530/190937745-dd150ea5-8677-4c93-9045-7f914c4b73fc.png)

**Comment by humkum** [comment]
Yes, we provided a recordId which is generated by Snowflake algorithm with schema id and version. And the new interface to getSchemaByRecordId also added in the new [pr](https://github.com/apache/rocketmq-schema-registry/pull/63).

**Comment by MatrixHB** [comment]
close by [PR #63](https://github.com/apache/rocketmq-schema-registry/pull/63)
