### ISSUE TITLE
Does not support Json schema conversion?

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq-schema-registry#64]
Schema conversion uses avro, which does not support json schema. If it is for verification, it can be put on the client

![image](https://user-images.githubusercontent.com/6446530/190996906-c34c4f02-ae34-483e-99a0-bcf06f2f04b9.png)

exception:

![image](https://user-images.githubusercontent.com/6446530/190997001-e3a93efe-c5f0-4fbf-83d4-5ee3e79eb882.png)

**Comment by sunxiaojian** [comment]
> Schema conversion uses avro, which does not support json schema. If it is for verification, it can be put on the client
> 
> ![image](https://user-images.githubusercontent.com/6446530/190996906-c34c4f02-ae34-483e-99a0-bcf06f2f04b9.png)
> 
> exception:
> 
> ![image](https://user-images.githubusercontent.com/6446530/190997001-e3a93efe-c5f0-4fbf-83d4-5ee3e79eb882.png)

Json schema use. :   https://github.com/everit-org/json-schema

**Comment by humkum** [comment]
This issue is same as the issue #57, and it will be fix in recent future. Json schema now provided is just like a pseudo avro schema type, user can only use avro schema idl format to generate schema idl, which is incorrect.
