### ISSUE TITLE
When the parameter tenant and schema are the same, and the subject is different, the registration will fail

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq-schema-registry#67]
tenent 和schema 不可能会经常变更，是否考虑更改校验的方式？对于connect 允许schema 是空的，不会强制要求，tenent如果对标的是namespace ，那可能一个集群是相同的
![image](https://user-images.githubusercontent.com/6446530/191721365-351ad40f-38d8-437d-8023-c38b107d86c8.png)

**Comment by ni-ze** [comment]
对于connect 允许schema 是空的，不会强制要求
-------
不是很明白这里，和注册schema报错关联不上

**Comment by sunxiaojian** [comment]
> ## 对于connect 允许schema 是空的，不会强制要求
> 不是很明白这里，和注册schema报错关联不上

这个我也记不清了，我应该是绕过了

**Comment by sunxiaojian** [comment]
> > ## 对于connect 允许schema 是空的，不会强制要求
> > 不是很明白这里，和注册schema报错关联不上
> 
> 这个我也记不清了，我应该是绕过了

先关掉吧，但是这个结构还是有待优化，内部这些实体的表示有些复杂，应该简洁一些
